### ISSUE TITLE
MT7622_7615_SoftAP_5.0.4.0_bb5ba3_20190503

### ISSUE THREAD

**Issue by MeIsReallyBa** [ferhung-mtk/asuswrt_RM2100#1]
[https://drive.google.com/file/d/1cO2GSyTrZKhdcLAiUFeA2e8WRgi1mg1h/view?usp=sharing](url)
和红米的官方固件驱动版本一致

**Comment by MeIsReallyBa** [comment]
还没有编译这个asuswrt，不过貌似wifi的hwnat没启用？

**Comment by ferhung-mtk** [comment]
目前发现2.4G速度很慢，还在看，HW_NAT还没时间看（虽然有PADAVAN现成的方法）！
另外，我这无法下载外网的资料

**Comment by MeIsReallyBa** [comment]
> 目前发现2.4G速度很慢，还在看，HW_NAT还没时间看（虽然有PADAVAN现成的方法）！
> 另外，我这无法下载外网的资料

https://sssddddff.lanzous.com/iwpqUdudiba 

另外MACHTTRANSMIT_SETTING.这个commit是解决的什么问题？

**Comment by ferhung-mtk** [comment]
MACHTTRANSMIT_SETTING 这个commit有些参数，完全是为了使驱动适应wireless log的显示，但是需要更多的测试，或许我应该使router去适应新的驱动。

**Comment by ferhung-mtk** [comment]
7615驱动已升级，7615的HW_NAT已加入。

**Comment by MeIsReallyBa** [comment]
> 7615驱动已升级，7615的HW_NAT已加入。

好的，另外这个固件的刷入分区位置能调整吗。。。。

**Comment by ferhung-mtk** [comment]
如果是NAND分区的话，具体看这个commit https://github.com/ferhung-mtk/asuswrt_RM2100/commit/3620d9fb54b8dc3ea6a6fd23541869b7f9bfad63
小米一般都是双分区，所以会有些麻烦，asuswrt有skip_bad_block的机制，可能对去除坏块有作用，详细方法没有研究，你可以看看

**Comment by MeIsReallyBa** [comment]
额看起来应该是刷入的第一个分区?

**Comment by MeIsReallyBa** [comment]
另外K2P的asuswrt的hwnat，应该要改接口名吧？一种是像hanwckf这样在hwnat的代码里增加rax0 https://github.com/hanwckf/rt-n56u/commit/45bcc5c9c7ecc9373653e3259baba9c63dbd0830 但在asuswrt里没找到ra_nat.c
另一种是直接将l1profile.dat的接口名改为原始的2G ra0 5G rai0。不过这样之前适配rax0的操作就要撤销了

**Comment by ferhung-mtk** [comment]
对的，不过rax0不是路由器本身固定了吗？除非进bootloader重写，否则单纯改为2G ra0 5G rai0，我觉得是没有用的。asuswrt里的ra_nat.c，华硕用的是prebuild（预编译）的，所以找不到。
另外，之前说RM2100的2.4G速度慢好像是我的路由器的2.4G挂了，刷回官方也是慢

**Comment by MeIsReallyBa** [comment]
> 对的，不过rax0不是路由器本身固定了吗？除非进bootloader重写，否则单纯改为2G ra0 5G rai0，我觉得是没有用的。asuswrt里的ra_nat.c，华硕用的是prebuild（预编译）的，所以找不到。
> 另外，之前说RM2100的2.4G速度慢好像是我的路由器的2.4G挂了，刷回官方也是慢

rax0这个名称是无线驱动根据l1profile.dat生成的，和bootloader没关系，你改下l1profile.dat里的接口名就知道了。我在padavan下试了可以改成2G ra0 5G rai0，改成ra0和rai0后，通过ifconfig rai0 up down是可以控制无线的

**Comment by ferhung-mtk** [comment]
刚试了一下，的确如此
