### ISSUE TITLE
软件中心

### ISSUE THREAD

**Issue by ghost** [ferhung-mtk/asuswrt_RM2100#2]
请问基于这个如何编译最新源码的shadowsocks-libev二进制文件？

**Comment by ferhung-mtk** [comment]
这是华硕官方的固件，没有Merlin功能，你试一试[rm2100-merlin](https://github.com/ferhung-mtk/rm2100-merlin)

shadowsocks的mipsel版本有现成的，用于Merlin的，你可以GitHub内自己再看看。

如果你需要编译的话需要修改ss的源码去适配编译工具，或许还需要适配Linux headers。

具体我没有试过。

**Comment by ghost** [comment]
之前留言找错地方了，现在已经安装好您编译的版本，也安装好了shadowsocks插件 ，软件中心web GUI一点开关就出现sh: /jffs/softcenter/scripts/: Permission denied 请问是哪里做错了？命令行可以 但就是感觉怪怪的

**Comment by ghost** [comment]
我只会搬运，能不能帮帮我?没找到mipsel bcm4706相关的tool chain

**Comment by ferhung-mtk** [comment]
rm2100-merlin那里如果无法安装ss，那是因为有禁止安装ss的源码，找到它，删掉看看。
如果安装了，无法使用，出现/jffs/softcenter/scripts/: Permission denied 可能是没有这个路径，你可以自己修改相应的路径。

**Comment by ghost** [comment]
不是无法安装。可以正常使用，就是不显示WEB GUI，禁止安装ss的源码是这个吗？
sed -i 's/\tdetect_package/\t# detect_package/g' /jffs/softcenter/scripts/ks_tar_intall.sh
jffs/softcenter/scripts这个路径有，也给了权限，还是一样不能显示web gui
这个固件有个问题 reboot之后打不开wifi 断电在恢复才能正常

**Comment by ghost** [comment]
请教一下如果不用merlinR,华硕官方改版装这个插件包可以用吗？感觉这个有维护
