### ISSUE TITLE
/jffs

### ISSUE THREAD

**Issue by ghost** [ferhung-mtk/asuswrt_RM2100#4]
您好 ，
MerlinR固件作者已经禁用了离线安装包，asuswrt-AC85U这个固件看到是没有允许jffs分区块，请问可以开放jffs分区吗？

**Comment by ferhung-mtk** [comment]
目前项目缺少维护，你可以follow MerlinR原作者的项目
[https://github.com/MerlinRdev/ac85p-merlin](https://github.com/MerlinRdev/ac85p-merlin)
