### ISSUE TITLE
RM-2100AC Issue and logs

### ISSUE THREAD

**Issue by CessXP** [ferhung-mtk/asuswrt_RM2100#5]
First issue, even in United States region mode, all WiFi channels appear in 5ghz 

![Screenshot_7](https://user-images.githubusercontent.com/31802781/102754778-15056400-4333-11eb-85c0-cdc608484d31.png)

And in 2.4 ghz WiFi I can see alot of "kernel: xxx, flush one!" and strange logs.

Dec 21 02:13:04 kernel: Start Seq = 00000000
Dec 21 02:13:10 kernel: 582, flush one!
Dec 21 02:13:19 kernel: BA - Send ADDBA request. StartSeq = 0,  FrameLen = 33. BufSize = 64
Dec 21 02:13:20 kernel: BA - Send ADDBA request. StartSeq = 1,  FrameLen = 33. BufSize = 64
Dec 21 02:13:34 kernel: Rcv Wcid(1) AddBAReq
Dec 21 02:13:34 kernel: Start Seq = 00000001
Dec 21 02:13:41 kernel: 4e0, flush one!
Dec 21 02:14:12 kernel: cb3, flush one!
Dec 21 02:15:09 kernel: PsRetrieveTimeout() Recover ps state(state 1 to state 0) [wcid = 5]!!
Dec 21 02:15:57 kernel: PsRetrieveTimeout() Recover ps state(state 1 to state 0) [wcid = 6]!!
Dec 21 02:16:03 kernel: PsRetrieveTimeout() Recover ps state(state 1 to state 5) [wcid = 6]!!
Dec 21 02:16:04 kernel: PsRetrieveTimeout() Recover ps state(state 1 to state 5) [wcid = 4]!!
Dec 21 02:16:04 kernel: PsRetrieveTimeout() Recover ps state(state 1 to state 0) [wcid = 6]!!
Dec 21 02:16:05 kernel: PsRetrieveTimeout() Recover ps state(state 1 to state 0) [wcid = 6]!!
Dec 21 02:16:26 kernel: PsRetrieveTimeout() Recover ps state(state 1 to state 5) [wcid = 2]!!
Dec 21 02:16:30 kernel: c, flush one!
Dec 21 02:17:13 kernel: 5b1, flush one!
Dec 21 02:17:15 kernel: Del Sta:2c:db:07:7d:ec:22
Dec 21 02:17:15 kernel: ---->CmdPsRetrieveStartRspFromCR Entry(wcid=3) left.
Dec 21 02:17:15 kernel: wcid=3, pEntry none when CmdPsClearRsp
Dec 21 02:17:16 kernel: New Sta:2c:db:07:7d:ec:22
Dec 21 02:17:16 kernel: AP SETKEYS DONE - AKMMap=WPA2PSK, PairwiseCipher=AES, GroupCipher=AES, wcid=2 from 2C:DB:07:7D:EC:22
Dec 21 02:17:16 kernel: PTK:d7980a5522a65734cbad25ee2a5b60dd799c953a9852eb532719d586066d225b106b062ad5c0fc767bcd3b2e5b2338a477f68cab6b373fefc60d23c33c382d18
Dec 21 02:17:16 kernel: Rcv Wcid(2) AddBAReq
Dec 21 02:17:16 kernel: Start Seq = 0000000e
Dec 21 02:17:17 kernel: HcGetEdca(): wdev=1, hobj is not ready!
Dec 21 02:17:17 kernel: HcGetEdca(): wdev=2, hobj is not ready!
Dec 21 02:17:17 kernel: HcGetEdca(): wdev=3, hobj is not ready!
Dec 21 02:17:17 kernel: HcGetEdca(): wdev=4, hobj is not ready!
Dec 21 02:17:17 kernel: HcGetEdca(): wdev=5, hobj is not ready!
Dec 21 02:17:17 kernel: HcGetEdca(): wdev=6, hobj is not ready!
Dec 21 02:17:19 kernel: PsRetrieveTimeout() Recover ps state(state 1 to state 0) [wcid = 4]!!
Dec 21 02:17:20 kernel: PsRetrieveTimeout() Recover ps state(state 1 to state 5) [wcid = 4]!!
Dec 21 02:17:22 kernel: PsRetrieveTimeout() Recover ps state(state 1 to state 0) [wcid = 6]!!
Dec 21 02:17:31 kernel: :MtCmdPktBudgetCtrl: bssid(255),wcid(65535),type(1)
Dec 21 02:17:32 kernel: :MtCmdPktBudgetCtrl: bssid(255),wcid(65535),type(0)
Dec 21 02:17:34 kernel: :MtCmdPktBudgetCtrl: bssid(255),wcid(65535),type(1)
Dec 21 02:17:35 kernel: :MtCmdPktBudgetCtrl: bssid(255),wcid(65535),type(0)
Dec 21 02:17:37 kernel: :MtCmdPktBudgetCtrl: bssid(255),wcid(65535),type(1)
Dec 21 02:17:38 kernel: :MtCmdPktBudgetCtrl: bssid(255),wcid(65535),type(0)
Dec 21 02:17:39 kernel: :MtCmdPktBudgetCtrl: bssid(255),wcid(65535),type(1)
Dec 21 02:17:40 kernel: :MtCmdPktBudgetCtrl: bssid(255),wcid(65535),type(0)
Dec 21 02:17:41 kernel: :MtCmdPktBudgetCtrl: bssid(255),wcid(65535),type(1)
Dec 21 02:17:42 kernel: :MtCmdPktBudgetCtrl: bssid(255),wcid(65535),type(0)
Dec 21 02:17:43 kernel: :MtCmdPktBudgetCtrl: bssid(255),wcid(65535),type(1)
Dec 21 02:17:44 kernel: :MtCmdPktBudgetCtrl: bssid(255),wcid(65535),type(0)
Dec 21 02:17:47 kernel: :MtCmdPktBudgetCtrl: bssid(255),wcid(65535),type(1)
Dec 21 02:17:48 kernel: :MtCmdPktBudgetCtrl: bssid(255),wcid(65535),type(0)
Dec 21 02:17:54 kernel: :MtCmdPktBudgetCtrl: bssid(255),wcid(65535),type(1)
Dec 21 02:17:55 kernel: :MtCmdPktBudgetCtrl: bssid(255),wcid(65535),type(0)
Dec 21 02:17:59 kernel: :MtCmdPktBudgetCtrl: bssid(255),wcid(65535),type(1)
Dec 21 02:18:00 kernel: :MtCmdPktBudgetCtrl: bssid(255),wcid(65535),type(0)
Dec 21 02:18:14 kernel: 784, flush one!
Dec 21 02:18:17 kernel: PsRetrieveTimeout() Recover ps state(state 1 to state 0) [wcid = 5]!!
Dec 21 02:18:18 kernel: PsRetrieveTimeout() Recover ps state(state 1 to state 0) [wcid = 5]!!
Dec 21 02:18:33 kernel: :MtCmdPktBudgetCtrl: bssid(255),wcid(65535),type(1)
Dec 21 02:18:35 kernel: :MtCmdPktBudgetCtrl: bssid(255),wcid(65535),type(0)
Dec 21 02:18:36 kernel: :MtCmdPktBudgetCtrl: bssid(255),wcid(65535),type(1)
Dec 21 02:18:37 kernel: :MtCmdPktBudgetCtrl: bssid(255),wcid(65535),type(0)
Dec 21 02:18:40 kernel: :MtCmdPktBudgetCtrl: bssid(255),wcid(65535),type(1)
Dec 21 02:18:41 kernel: :MtCmdPktBudgetCtrl: bssid(255),wcid(65535),type(0)
Dec 21 02:18:42 kernel: e6c, flush one!
Dec 21 02:18:44 kernel: :MtCmdPktBudgetCtrl: bssid(255),wcid(65535),type(1)
Dec 21 02:18:45 kernel: :MtCmdPktBudgetCtrl: bssid(255),wcid(65535),type(0)
Dec 21 02:18:45 kernel: 4b1, flush one!
Dec 21 02:18:46 kernel: :MtCmdPktBudgetCtrl: bssid(255),wcid(65535),type(1)
Dec 21 02:18:47 kernel: :MtCmdPktBudgetCtrl: bssid(255),wcid(65535),type(0)
Dec 21 02:18:47 kernel: PsRetrieveTimeout() Recover ps state(state 1 to state 0) [wcid = 6]!!
Dec 21 02:18:49 kernel: :MtCmdPktBudgetCtrl: bssid(255),wcid(65535),type(1)
Dec 21 02:18:50 kernel: :MtCmdPktBudgetCtrl: bssid(255),wcid(65535),type(0)
Dec 21 02:18:57 kernel: :MtCmdPktBudgetCtrl: bssid(255),wcid(65535),type(1)
Dec 21 02:18:58 kernel: :MtCmdPktBudgetCtrl: bssid(255),wcid(65535),type(0)
Dec 21 02:18:58 kernel: PsRetrieveTimeout() Recover ps state(state 1 to state 5) [wcid = 6]!!
Dec 21 02:19:01 kernel: :MtCmdPktBudgetCtrl: bssid(255),wcid(65535),type(1)
Dec 21 02:19:02 kernel: :MtCmdPktBudgetCtrl: bssid(255),wcid(65535),type(0)
Dec 21 02:19:05 kernel: PsRetrieveTimeout() Recover ps state(state 1 to state 0) [wcid = 6]!!
Dec 21 02:19:53 kernel: BA - Send ADDBA request. StartSeq = 4,  FrameLen = 33. BufSize = 64
Dec 21 02:20:36 kernel: :MtCmdPktBudgetCtrl: bssid(255),wcid(65535),type(1)
Dec 21 02:20:37 kernel: :MtCmdPktBudgetCtrl: bssid(255),wcid(65535),type(0)
Dec 21 02:21:43 kernel: 6db, flush one!
Dec 21 02:23:36 kernel: 87c, flush one!
Dec 21 02:24:58 kernel: Del Sta:0e:ae:b3:2b:fb:34
Dec 21 02:24:59 kernel: HcGetEdca(): wdev=1, hobj is not ready!
Dec 21 02:24:59 kernel: HcGetEdca(): wdev=2, hobj is not ready!
Dec 21 02:24:59 kernel: HcGetEdca(): wdev=3, hobj is not ready!
Dec 21 02:24:59 kernel: HcGetEdca(): wdev=4, hobj is not ready!
Dec 21 02:24:59 kernel: HcGetEdca(): wdev=5, hobj is not ready!
Dec 21 02:24:59 kernel: HcGetEdca(): wdev=6, hobj is not ready!
Dec 21 02:25:01 kernel: AP SETKEYS DONE - WPA2, AuthMode(7)=WPA2PSK, WepStatus(6)=AES, GroupWepStatus(6)=AES
Dec 21 02:25:02 kernel: Rcv Wcid(3) AddBAReq
Dec 21 02:25:02 kernel: Start Seq = 00000000
Dec 21 02:25:04 kernel: BA - Send ADDBA request. StartSeq = 2,  FrameLen = 33. BufSize = 64
Dec 21 02:25:07 kernel: BA - Send ADDBA request. StartSeq = 0,  FrameLen = 33. BufSize = 64
Dec 21 02:25:21 kernel: BA - Send ADDBA request. StartSeq = 1,  FrameLen = 33. BufSize = 64
Dec 21 02:25:28 kernel: Rcv Wcid(3) AddBAReq
Dec 21 02:25:28 kernel: Start Seq = 00000001
Dec 21 02:25:30 kernel: BA - Send ADDBA request. StartSeq = 5,  FrameLen = 33. BufSize = 64
Dec 21 02:25:45 kernel: :MtCmdPktBudgetCtrl: bssid(255),wcid(65535),type(1)
Dec 21 02:25:47 kernel: :MtCmdPktBudgetCtrl: bssid(255),wcid(65535),type(0)
Dec 21 02:25:50 kernel: :MtCmdPktBudgetCtrl: bssid(255),wcid(65535),type(1)
Dec 21 02:25:51 kernel: :MtCmdPktBudgetCtrl: bssid(255),wcid(65535),type(0)
Dec 21 02:26:01 kernel: BA - Send ADDBA request. StartSeq = 0,  FrameLen = 33. BufSize = 64
Dec 21 02:26:03 kernel: 1d0, flush one!

**Comment by CessXP** [comment]
And I have full WiFi icon but the speed of the 2.4ghz at some meters  is really poor.

**Comment by ferhung-mtk** [comment]
YEAP! I will disable more logs in 5GHz.

**Comment by CessXP** [comment]
> YEAP! I will disable more logs in 5GHz.

Thanks sir, I detected too some disconnections in 2.4ghz, sometimes happens.

**Comment by ferhung-mtk** [comment]
OK, I need time to debug.

**Comment by padcom** [comment]
@ferhung-mtk Did you figure out what was going on?
